### PR TITLE
Rockets Render

### LINKED ISSUE #5: [1pt] Switch badges for Rockets - Conditional components
Rockets that have already been reserved should show a "Reserved" badge and "Cancel reservation" button instead of the default "Reserve rocket" (as per design)

Use the React conditional rendering syntax:
```javascript
{rocket.reserved && ( 
    // render Cancel Rocket button
)}
```

### LINKED ISSUE #13: [4pt] Display rockets - Lists render
- Use `useSelector()` Redux Hook to select the state slices and render lists of rockets in corresponding routes. i.e.:
```javascript
// get rockets data from the store
const rockets = useSelector(state => state.rockets);
```

- You can style the whole application "by hand" or you could use [React Bootstrap](https://react-bootstrap.github.io/), a UI library that could speed up the process. This is a popular library and working with its components would be good practice.
- Render a list of rockets (as per design). For the image of a rocket use the first image in the array of `flickr_images`.

### PR DESCRIPTION
**Pull request by KDlamini**
In this feature, I will:
- Use `useSelector()` Redux Hook to select the state slices and render lists of rockets in corresponding routes.
- Render a list of rockets.
-  Add styling to Rocket component.
- Rockets that have already been reserved should show a "Reserved" badge and "Cancel reservation" button instead of the default "Reserve rocket"

### CODE REVIEW

**Review by Leandro-Barretoo — CHANGES_REQUESTED** [review]
Great work so far but there is some issues to fix.

1. The fetch is again doing fetch everytime you go to rockets tap. It can only happen once.
2. When starting the app the route is '/' and nothing is being display, I should have the rockets displayed in the '/' and '/rockets'.

**Comment by KDlamini** [comment]
@Leandro-Barretoo The reason is that I didn't have the code from the `Fetch Rockets` PR yet. It would have been updated when I merged the `Fetch Rockets` PR and resolved conflicts if you had reviewed the PR a lot faster since I finished it quite a while back during program hours...

Also merging PR's ahead of this one is also causing new conflicts on this PR that would have been avoided if this PR was merged first.  Therefore, I basically have to wait for this PR to be approved and merged first before I can merge the rest to avoid a conflict nightmare from PR's ahead... That is a huge inconvenience.

**Review by Leandro-Barretoo — CHANGES_REQUESTED** [review]
The route '/' is still empty, It should have the rockets displayed.

**Review by Leandro-Barretoo — APPROVED** [review]
Its approved!! Good work

**Pull request merged**
